export const langNameMappings: Record<string, string> = {
  ar: "العربية",
  zh: "简体中文",
  zhtw: "繁體中文",
  cs: "Čeština",
  hr: "Hrvatski",
  da: "Dansk",
  nl: "Nederlands",
  el: "Ελληνικά",
  en: "English",
  en_US: "English (US)",
  fi: "Suomi",
  fr: "Français",
  ga: "Gaeilge",
  gl: "Galego",
  de: "Deutsch",
  hu: "Magyar",
  it: "Italiano",
  ja: "日本語",
  ko: "한국어",
  nb_NO: "Norsk bokmål",
  pl: "Polski",
  pt: "Português",
  pt_BR: "Português (Brasil)",
  ro: "Română",
  ru: "Русский",
  sk: "Slovenčina",
  sl: "Slovenščina",
  es: "Español",
  sv: "Svenska",
  tr: "Türkçe",
  uk: "Українська",
  vi: "Tiếng Việt",
};

export const supportedLangs = Object.keys(langNameMappings);
